// 仅导出公共数据协议，上下文管理和提示词组装留待后续实现。
export type {
  AgentContext,
  ContextBudget,
  ContextEntry,
  ContextFrame,
  ContextFrameId,
  ContextLesson,
  ContextLevel,
  ContextMemory,
  ContextObservation,
  ContextPhase,
  ContextReference,
  ContextReplan,
  ContextSummary,
  ContextTask,
  ContextTaskChain,
  ContextTaskDefinition,
  ContextTaskId,
  ContextTaskRef,
  ContextTaskState,
  ContextValue,
  LevelOneContext,
  LevelThreeContext,
  LevelTwoContext,
} from './api.js';
